In [1]:
#To show multiple outputs and misc. changes
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # Show all results without print (last_expr)

In [2]:
import pandas as pd 
import numpy as np

In [14]:
np.random.randn()
print("*" * 50)
np.random.randn(1, 1)
print("*" * 50)
np.random.randn(2,1)
print("*" * 50)
np.random.randn(2, 1).cumsum(axis=0)


2.1033480356321532

**************************************************


array([[-0.24144975]])

**************************************************


array([[-1.900627  ],
       [ 0.70720667]])

**************************************************


array([[0.70567233],
       [1.83383688]])

In [18]:
a = np.random.randn(2,1)
a
a.cumsum(axis=0)

print("*" * 50)

b = np.random.randn(1, 1)
b
b[-1, :]

print("*" * 50)

b + a.cumsum(axis=0)
b[-1, :] + a.cumsum(axis=0)

array([[ 0.85509592],
       [-0.49923511]])

array([[0.85509592],
       [0.35586081]])

**************************************************


array([[-1.06168338]])

array([-1.06168338])

**************************************************


array([[-0.20658746],
       [-0.70582257]])

array([[-0.20658746],
       [-0.70582257]])

In [20]:
-1.06168338 + 0.85509592
-1.06168338 + 0.35586081

-0.20658746000000006

-0.70582257

In [21]:
last_rows = np.random.randn(1, 1)
new_rows = last_rows[-1, :] + np.random.randn(50, 1).cumsum(axis=0)

In [27]:
binom_dist = np.random.binomial(n=1, p=0.5, size=1000)
binom_dist

np.random.choice(binom_dist, 100, replace=True).mean()

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,

0.51